### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by TE-N-ElvenWang** [LiangYang666/ChatGPT-Web#24]
Seen below error sometime, not found the way to fix...

[2023-04-11 16:57:05,799] ERROR in app: Exception on /loadHistory [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/home/user/.local/lib/python3.8/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/home/user/.local/lib/python3.8/site-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

**Comment by LiangYang666** [comment]
这可能是flask版本的原因，你可以尝试 `pip install flask --upgrade`升级flask版本试一下

This may be the reason for the flask version, you can try `pip install flask --upgrade` to upgrade the flask version and try again,

**Comment by TE-N-ElvenWang** [comment]
Appreciate for your response in time! now it is working.
