### ISSUE TITLE
打包成单独exe后，报错。

### ISSUE THREAD

**Issue by 5777033** [LiangYang666/ChatGPT-Web#29]
您好，打包成单独exe后，报错。
Traceback (most recent call last):
  File "main.py", line 681, in <module>
  File "flask\app.py", line 884, in run
  File "flask\cli.py", line 723, in show_server_banner
  File "click\utils.py", line 299, in echo
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by LiangYang666** [comment]
我之前也尝试打包出了问题，后面就没弄了

**Comment by cpfdd** [comment]
在打包的命令后面加上-c就可以了

**Comment by 5777033** [comment]
感谢大佬，打包成功。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiangYang666/ChatGPT-Web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月5日(星期五) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiangYang666/ChatGPT-Web] 打包成单独exe后，报错。 (Issue #29)





 
在打包的命令后面加上-c就可以了
